/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.CardLayout;
import java.awt.FontFormatException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author julio
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
 
    public Principal() {
        setResizable(false);
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRoot = new javax.swing.JPanel();
        PanelCadUsu = new javax.swing.JPanel();
        LabelEditUsu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textNome1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        textSobrenome1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textCSenha = new javax.swing.JPasswordField();
        textSenha = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        textJogoFavorito = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        buttonCadastrarUsuario1 = new javax.swing.JButton();
        ComboBoxGen = new javax.swing.JComboBox<>();
        jTabbedCadJogo = new javax.swing.JTabbedPane();
        PanelCadJogo = new javax.swing.JPanel();
        LabelCadUsu1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        textNome2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        textSobrenome2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        textEmail1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        buttonCadastrarUsuario2 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        PanelAvaJogo = new javax.swing.JPanel();
        LabelCadUsu2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonCadastrarUsuario = new javax.swing.JButton();
        jComboBoxAudio = new javax.swing.JComboBox<>();
        jComboBoxJogabilidade = new javax.swing.JComboBox<>();
        jComboBoxGraficos = new javax.swing.JComboBox<>();
        jComboBoxEnredo = new javax.swing.JComboBox<>();
        buttonCadastrarUsuario3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxAudio1 = new javax.swing.JComboBox<>();
        PanelEditJogo = new javax.swing.JPanel();
        LabelCadUsu3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        textNome3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        textSobrenome3 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        textEmail2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        buttonCadastrarUsuario5 = new javax.swing.JButton();
        PanelLateral = new javax.swing.JPanel();
        jButtonEditUsu = new javax.swing.JButton();
        jButtonLogoff = new javax.swing.JButton();
        jButtonCadJogo = new javax.swing.JButton();
        jButtonEditJogo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MenuBarPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemNewUsu = new javax.swing.JMenuItem();
        MenuItemNewAva = new javax.swing.JMenuItem();
        MenuItemNewJogo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItemEditUsu = new javax.swing.JMenuItem();
        MenuItemEditAva = new javax.swing.JMenuItem();
        MenuItemEditJogo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelRoot.setPreferredSize(new java.awt.Dimension(600, 579));
        PanelRoot.setLayout(new java.awt.CardLayout());

        PanelCadUsu.setBackground(new java.awt.Color(236, 239, 249));

        LabelEditUsu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelEditUsu.setText("EDITAR USUÁRIO");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Nome:");

        textNome1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNome1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Sobrenome:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Email:");

        textEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        textSobrenome1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Senha:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Confirme a senha:");

        textCSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCSenhaActionPerformed(evt);
            }
        });

        textSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenhaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Genero Favorito:");

        textJogoFavorito.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textJogoFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJogoFavoritoActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Jogo Favorito:");

        buttonCadastrarUsuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/b8013d3077f62d29bce2664db69424.png"))); // NOI18N
        buttonCadastrarUsuario1.setToolTipText("Salvar");
        buttonCadastrarUsuario1.setAutoscrolls(true);
        buttonCadastrarUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarUsuario1ActionPerformed(evt);
            }
        });

        ComboBoxGen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FPS", "Terror", "Ação/Aventura", "RPG", "Plataforma", "Luta", "Corrida", "Esportes" }));
        ComboBoxGen.setPreferredSize(new java.awt.Dimension(74, 25));
        ComboBoxGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxGenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCadUsuLayout = new javax.swing.GroupLayout(PanelCadUsu);
        PanelCadUsu.setLayout(PanelCadUsuLayout);
        PanelCadUsuLayout.setHorizontalGroup(
            PanelCadUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadUsuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(PanelCadUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadUsuLayout.createSequentialGroup()
                        .addGroup(PanelCadUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(LabelEditUsu))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadUsuLayout.createSequentialGroup()
                        .addGroup(PanelCadUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelCadUsuLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(textJogoFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCadUsuLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(53, 53, 53)
                                .addGroup(PanelCadUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textCSenha)
                                    .addGroup(PanelCadUsuLayout.createSequentialGroup()
                                        .addGroup(PanelCadUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                                            .addComponent(textSobrenome1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                                            .addComponent(textNome1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                                            .addComponent(textSenha))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(ComboBoxGen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(38, 38, 38))))
            .addGroup(PanelCadUsuLayout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(buttonCadastrarUsuario1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelCadUsuLayout.setVerticalGroup(
            PanelCadUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadUsuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(LabelEditUsu)
                .addGap(18, 18, 18)
                .addGroup(PanelCadUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSobrenome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(PanelCadUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PanelCadUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textJogoFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(buttonCadastrarUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        PanelRoot.add(PanelCadUsu, "PanelEditUsu");

        PanelCadJogo.setBackground(new java.awt.Color(236, 239, 249));

        LabelCadUsu1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelCadUsu1.setText("CADASTRAR JOGO");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Nome:");

        textNome2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Desenvolvedora:");

        textSobrenome2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Produtora:");

        textEmail1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Data de lançamento:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Gênero:");

        buttonCadastrarUsuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_403-512 (1).png"))); // NOI18N
        buttonCadastrarUsuario2.setAutoscrolls(true);
        buttonCadastrarUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarUsuario2ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FPS", "Terror", "Ação/Aventura", "RPG", "Plataforma", "Luta", "Corrida", "Esportes" }));
        jComboBox5.setPreferredSize(new java.awt.Dimension(98, 25));

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextField1.setPreferredSize(new java.awt.Dimension(6, 25));

        javax.swing.GroupLayout PanelCadJogoLayout = new javax.swing.GroupLayout(PanelCadJogo);
        PanelCadJogo.setLayout(PanelCadJogoLayout);
        PanelCadJogoLayout.setHorizontalGroup(
            PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadJogoLayout.createSequentialGroup()
                .addGroup(PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadJogoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCadUsu1)
                            .addGroup(PanelCadJogoLayout.createSequentialGroup()
                                .addGroup(PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20))
                                .addGap(44, 44, 44)
                                .addGroup(PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textSobrenome2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(PanelCadJogoLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(buttonCadastrarUsuario2)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        PanelCadJogoLayout.setVerticalGroup(
            PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadJogoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(LabelCadUsu1)
                .addGap(49, 49, 49)
                .addGroup(PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSobrenome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(buttonCadastrarUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        jTabbedCadJogo.addTab("Cadastrar jogo", PanelCadJogo);

        PanelAvaJogo.setBackground(new java.awt.Color(236, 239, 249));

        LabelCadUsu2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelCadUsu2.setText("AVALIAR JOGO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Enredo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Gráficos:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Jogabilidade:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Áudio:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Comentários:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        buttonCadastrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/b8013d3077f62d29bce2664db69424.png"))); // NOI18N
        buttonCadastrarUsuario.setAutoscrolls(true);
        buttonCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarUsuarioActionPerformed(evt);
            }
        });

        jComboBoxAudio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Péssimo", "Ruim", "Regular", "Bom", "Excelente" }));
        jComboBoxAudio.setSelectedIndex(-1);
        jComboBoxAudio.setPreferredSize(new java.awt.Dimension(72, 25));

        jComboBoxJogabilidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Péssimo", "Ruim", "Regular", "Bom", "Excelente" }));
        jComboBoxJogabilidade.setSelectedIndex(-1);
        jComboBoxJogabilidade.setPreferredSize(new java.awt.Dimension(72, 25));

        jComboBoxGraficos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Péssimo", "Ruim", "Regular", "Bom", "Excelente" }));
        jComboBoxGraficos.setSelectedIndex(-1);
        jComboBoxGraficos.setPreferredSize(new java.awt.Dimension(72, 25));

        jComboBoxEnredo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Péssimo", "Ruim", "Regular", "Bom", "Excelente" }));
        jComboBoxEnredo.setSelectedIndex(-1);
        jComboBoxEnredo.setPreferredSize(new java.awt.Dimension(72, 25));

        buttonCadastrarUsuario3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_402-512 (2).png"))); // NOI18N
        buttonCadastrarUsuario3.setAutoscrolls(true);
        buttonCadastrarUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarUsuario3ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Conteúdo:");

        jComboBoxAudio1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Péssimo", "Ruim", "Regular", "Bom", "Excelente" }));
        jComboBoxAudio1.setSelectedIndex(-1);
        jComboBoxAudio1.setPreferredSize(new java.awt.Dimension(72, 25));

        javax.swing.GroupLayout PanelAvaJogoLayout = new javax.swing.GroupLayout(PanelAvaJogo);
        PanelAvaJogo.setLayout(PanelAvaJogoLayout);
        PanelAvaJogoLayout.setHorizontalGroup(
            PanelAvaJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAvaJogoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(PanelAvaJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelCadUsu2)
                    .addGroup(PanelAvaJogoLayout.createSequentialGroup()
                        .addGroup(PanelAvaJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel21))
                        .addGap(79, 79, 79)
                        .addGroup(PanelAvaJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxEnredo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxJogabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxAudio1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelAvaJogoLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(buttonCadastrarUsuario3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCadastrarUsuario)
                                .addGap(177, 177, 177)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PanelAvaJogoLayout.setVerticalGroup(
            PanelAvaJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAvaJogoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(LabelCadUsu2)
                .addGap(18, 18, 18)
                .addGroup(PanelAvaJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEnredo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAvaJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAvaJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxJogabilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAvaJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelAvaJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAudio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelAvaJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(PanelAvaJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCadastrarUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedCadJogo.addTab("Avaliar jogo", PanelAvaJogo);

        PanelRoot.add(jTabbedCadJogo, "cardTab");

        PanelEditJogo.setBackground(new java.awt.Color(236, 239, 249));

        LabelCadUsu3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelCadUsu3.setText("EDITAR JOGO");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Nome:");

        textNome3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Desenvolvedora:");

        textSobrenome3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Produtora:");

        textEmail2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Data de lançamento:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Gênero:");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FPS", "Terror", "Ação/Aventura", "RPG", "Plataforma", "Luta", "Corrida", "Esportes" }));
        jComboBox6.setPreferredSize(new java.awt.Dimension(98, 25));

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextField2.setPreferredSize(new java.awt.Dimension(6, 25));

        buttonCadastrarUsuario5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/b8013d3077f62d29bce2664db69424.png"))); // NOI18N
        buttonCadastrarUsuario5.setAutoscrolls(true);
        buttonCadastrarUsuario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarUsuario5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEditJogoLayout = new javax.swing.GroupLayout(PanelEditJogo);
        PanelEditJogo.setLayout(PanelEditJogoLayout);
        PanelEditJogoLayout.setHorizontalGroup(
            PanelEditJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditJogoLayout.createSequentialGroup()
                .addGroup(PanelEditJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEditJogoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(PanelEditJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCadUsu3)
                            .addGroup(PanelEditJogoLayout.createSequentialGroup()
                                .addGroup(PanelEditJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel26))
                                .addGap(44, 44, 44)
                                .addGroup(PanelEditJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textSobrenome3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelEditJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBox6, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(PanelEditJogoLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(buttonCadastrarUsuario5)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        PanelEditJogoLayout.setVerticalGroup(
            PanelEditJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEditJogoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(LabelCadUsu3)
                .addGap(49, 49, 49)
                .addGroup(PanelEditJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEditJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSobrenome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEditJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEditJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEditJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(buttonCadastrarUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        PanelRoot.add(PanelEditJogo, "PanelEditJogo");

        PanelLateral.setBackground(new java.awt.Color(43, 64, 136));
        PanelLateral.setPreferredSize(new java.awt.Dimension(200, 579));
        PanelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEditUsu.setBackground(new java.awt.Color(236, 239, 249));
        jButtonEditUsu.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonEditUsu.setText("Editar Usuário");
        jButtonEditUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditUsuActionPerformed(evt);
            }
        });
        PanelLateral.add(jButtonEditUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 50));

        jButtonLogoff.setBackground(new java.awt.Color(236, 239, 249));
        jButtonLogoff.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonLogoff.setText("Sair");
        jButtonLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoffActionPerformed(evt);
            }
        });
        PanelLateral.add(jButtonLogoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 200, 50));

        jButtonCadJogo.setBackground(new java.awt.Color(236, 239, 249));
        jButtonCadJogo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonCadJogo.setText("Cadastrar Jogo");
        jButtonCadJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadJogoActionPerformed(evt);
            }
        });
        PanelLateral.add(jButtonCadJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 50));

        jButtonEditJogo.setBackground(new java.awt.Color(236, 239, 249));
        jButtonEditJogo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonEditJogo.setText("Editar Jogo");
        jButtonEditJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditJogoActionPerformed(evt);
            }
        });
        PanelLateral.add(jButtonEditJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/video-game-emoji-png-7-2.png"))); // NOI18N
        PanelLateral.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jMenu1.setText("Novo");

        MenuItemNewUsu.setText("Usuário");
        MenuItemNewUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemNewUsuActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemNewUsu);

        MenuItemNewAva.setText("Avaliação");
        MenuItemNewAva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemNewAvaActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemNewAva);

        MenuItemNewJogo.setText("Jogo");
        MenuItemNewJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemNewJogoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemNewJogo);

        MenuBarPrincipal.add(jMenu1);

        jMenu2.setText("Editar");

        MenuItemEditUsu.setText("Usuário");
        MenuItemEditUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEditUsuActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemEditUsu);

        MenuItemEditAva.setText("Avaliação");
        jMenu2.add(MenuItemEditAva);

        MenuItemEditJogo.setText("Jogo");
        jMenu2.add(MenuItemEditJogo);

        MenuBarPrincipal.add(jMenu2);

        jMenu3.setText("Sobre");
        MenuBarPrincipal.add(jMenu3);

        setJMenuBar(MenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(PanelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemNewUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemNewUsuActionPerformed
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "PanelCadUsu");
    }//GEN-LAST:event_MenuItemNewUsuActionPerformed

    private void MenuItemEditUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEditUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemEditUsuActionPerformed

    private void MenuItemNewAvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemNewAvaActionPerformed
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "PanelAvaJogo");
    }//GEN-LAST:event_MenuItemNewAvaActionPerformed

    private void MenuItemNewJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemNewJogoActionPerformed
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "PanelCadJogo");
    }//GEN-LAST:event_MenuItemNewJogoActionPerformed

    private void buttonCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastrarUsuarioActionPerformed

    private void textNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNome1ActionPerformed

    private void textCSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCSenhaActionPerformed

    private void textSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSenhaActionPerformed

    private void textJogoFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJogoFavoritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textJogoFavoritoActionPerformed

    private void buttonCadastrarUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarUsuario1ActionPerformed
        
    }//GEN-LAST:event_buttonCadastrarUsuario1ActionPerformed

    private void buttonCadastrarUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarUsuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastrarUsuario2ActionPerformed

    private void ComboBoxGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxGenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxGenActionPerformed

    private void jButtonEditJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditJogoActionPerformed
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "PanelEditJogo");
    }//GEN-LAST:event_jButtonEditJogoActionPerformed

    private void jButtonCadJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadJogoActionPerformed
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "cardTab");
    }//GEN-LAST:event_jButtonCadJogoActionPerformed

    private void jButtonLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoffActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLogoffActionPerformed

    private void jButtonEditUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditUsuActionPerformed
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "PanelEditUsu");
    }//GEN-LAST:event_jButtonEditUsuActionPerformed

    private void buttonCadastrarUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarUsuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastrarUsuario3ActionPerformed

    private void buttonCadastrarUsuario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarUsuario5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastrarUsuario5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FontFormatException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxGen;
    private javax.swing.JLabel LabelCadUsu1;
    private javax.swing.JLabel LabelCadUsu2;
    private javax.swing.JLabel LabelCadUsu3;
    private javax.swing.JLabel LabelEditUsu;
    private javax.swing.JMenuBar MenuBarPrincipal;
    private javax.swing.JMenuItem MenuItemEditAva;
    private javax.swing.JMenuItem MenuItemEditJogo;
    private javax.swing.JMenuItem MenuItemEditUsu;
    private javax.swing.JMenuItem MenuItemNewAva;
    private javax.swing.JMenuItem MenuItemNewJogo;
    private javax.swing.JMenuItem MenuItemNewUsu;
    private javax.swing.JPanel PanelAvaJogo;
    private javax.swing.JPanel PanelCadJogo;
    private javax.swing.JPanel PanelCadUsu;
    private javax.swing.JPanel PanelEditJogo;
    private javax.swing.JPanel PanelLateral;
    private javax.swing.JPanel PanelRoot;
    private javax.swing.JButton buttonCadastrarUsuario;
    private javax.swing.JButton buttonCadastrarUsuario1;
    private javax.swing.JButton buttonCadastrarUsuario2;
    private javax.swing.JButton buttonCadastrarUsuario3;
    private javax.swing.JButton buttonCadastrarUsuario5;
    private javax.swing.JButton jButtonCadJogo;
    private javax.swing.JButton jButtonEditJogo;
    private javax.swing.JButton jButtonEditUsu;
    private javax.swing.JButton jButtonLogoff;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBoxAudio;
    private javax.swing.JComboBox<String> jComboBoxAudio1;
    private javax.swing.JComboBox<String> jComboBoxEnredo;
    private javax.swing.JComboBox<String> jComboBoxGraficos;
    private javax.swing.JComboBox<String> jComboBoxJogabilidade;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedCadJogo;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPasswordField textCSenha;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textEmail1;
    private javax.swing.JTextField textEmail2;
    private javax.swing.JTextField textJogoFavorito;
    private javax.swing.JTextField textNome1;
    private javax.swing.JTextField textNome2;
    private javax.swing.JTextField textNome3;
    private javax.swing.JPasswordField textSenha;
    private javax.swing.JTextField textSobrenome1;
    private javax.swing.JTextField textSobrenome2;
    private javax.swing.JTextField textSobrenome3;
    // End of variables declaration//GEN-END:variables
}
