/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import DAO.AvaliacaoDAO;
import DAO.UsuarioDAO;
import controle.AvaliacaoRecursoController;
import controle.ValidarCampos;
import controle.ControleBD;
import controle.GerarRelatorios;
import controle.JogoRecursoController;
import java.awt.CardLayout;
import java.awt.FontFormatException;
import java.awt.HeadlessException;
import java.io.IOException;
import static java.lang.Double.parseDouble;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Avaliacao;
import modelo.Jogo;
import modelo.Usuario;


/**
 *
 * @author julio
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Usuario u = new Usuario();
    UsuarioDAO ud= new UsuarioDAO();
    ValidarCampos vc = new ValidarCampos();
    Jogo j = new Jogo();
    Avaliacao a = new Avaliacao();
    ValidarCampos v = new ValidarCampos();

    ControleBD controlBD = new ControleBD();
    ArrayList<String> aux = new ArrayList();
    ArrayList<String> jogo = new ArrayList();
    ArrayList<String> aval = new ArrayList();
    ArrayList<String> usu = new ArrayList();
    
    GerarRelatorios rep = new GerarRelatorios();
    
    JogoRecursoController controlJogo = new JogoRecursoController();
    AvaliacaoRecursoController controlAval = new AvaliacaoRecursoController();
    int i = -1;
    
    public static final String pdf = 
            System.getProperty("user.dir")+"/src/Relatorios/relatorioCompleto.pdf";
    public static final String relatorio = 
            System.getProperty("user.dir")+"/src/Relatorios/RelatorioCompleto.jasper";
    
    public static final String pdf1 = 
            System.getProperty("user.dir")+"/src/Relatorios/relatorioGenero.pdf";
    public static final String relatorio1 = 
            System.getProperty("user.dir")+"/src/Relatorios/RelatorioGroupJogo.jasper";
    
    public static final String pdf2 = 
            System.getProperty("user.dir")+"/src/Relatorios/relatorioParam.pdf";
    public static final String relatorio2 = 
            System.getProperty("user.dir")+"/src/Relatorios/RelatorioParametro.jasper";
    
    AvaliacaoDAO avaDAO = new AvaliacaoDAO();

    public Principal() {
        setResizable(false);
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRoot = new javax.swing.JPanel();
        PanelInicial = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PanelEditUsu = new javax.swing.JPanel();
        LabelEditUsu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textEditNomeUsu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textEditEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textEditCSenha = new javax.swing.JPasswordField();
        textEditSenha = new javax.swing.JPasswordField();
        buttonEditUser = new javax.swing.JButton();
        buttonDeleteUser = new javax.swing.JButton();
        PanelCadJogo = new javax.swing.JPanel();
        LabelCadUsu1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        textNomeJogo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        textDesenvolvedora = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        buttonCadastrarUsuario2 = new javax.swing.JButton();
        comboGeneroJogo = new javax.swing.JComboBox<>();
        PanelCadJogo1 = new javax.swing.JPanel();
        LabelEditJogo = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        editNomeJogo = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        editDesenvolvedora = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        buttonAvancarEditJogo = new javax.swing.JButton();
        editGenero = new javax.swing.JComboBox<>();
        deleteJogo = new javax.swing.JButton();
        avaliar = new javax.swing.JButton();
        PanelListGame = new javax.swing.JPanel();
        LabelListGame = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        PanelListAva = new javax.swing.JPanel();
        LabelListGame1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaAval = new javax.swing.JTable();
        editarAval = new javax.swing.JButton();
        minhasAval1 = new javax.swing.JButton();
        excluirAval = new javax.swing.JButton();
        PanelCadAval = new javax.swing.JPanel();
        LabelCadAval = new javax.swing.JLabel();
        labelNomeAval = new javax.swing.JLabel();
        textNomeAval = new javax.swing.JTextField();
        labelDev = new javax.swing.JLabel();
        textDevAval = new javax.swing.JTextField();
        labelGen = new javax.swing.JLabel();
        comboGenAval = new javax.swing.JComboBox<>();
        labelNota = new javax.swing.JLabel();
        textNota = new javax.swing.JFormattedTextField();
        labelAval = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        textAval = new javax.swing.JTextArea();
        salvarAval = new javax.swing.JButton();
        editarAvaliacao = new javax.swing.JButton();
        PanelLateral = new javax.swing.JPanel();
        jButtonEditUsu = new javax.swing.JButton();
        jButtonLogoff = new javax.swing.JButton();
        jButtonCadJogo = new javax.swing.JButton();
        jButtonListGames = new javax.swing.JButton();
        jButtonListAva = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelRoot.setPreferredSize(new java.awt.Dimension(600, 579));
        PanelRoot.setLayout(new java.awt.CardLayout());

        PanelInicial.setBackground(new java.awt.Color(236, 239, 249));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/video-game-emoji-png-7 (1).png"))); // NOI18N

        javax.swing.GroupLayout PanelInicialLayout = new javax.swing.GroupLayout(PanelInicial);
        PanelInicial.setLayout(PanelInicialLayout);
        PanelInicialLayout.setHorizontalGroup(
            PanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicialLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel2)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        PanelInicialLayout.setVerticalGroup(
            PanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicialLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel2)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        PanelRoot.add(PanelInicial, "PanelInicial");

        PanelEditUsu.setBackground(new java.awt.Color(236, 239, 249));

        LabelEditUsu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelEditUsu.setText("EDITAR USUÁRIO");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Nome:");

        textEditNomeUsu.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textEditNomeUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEditNomeUsuActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Email:");

        textEditEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textEditEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEditEmailActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Senha:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Confirme a senha:");

        textEditCSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEditCSenhaActionPerformed(evt);
            }
        });

        textEditSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEditSenhaActionPerformed(evt);
            }
        });

        buttonEditUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/b8013d3077f62d29bce2664db69424.png"))); // NOI18N
        buttonEditUser.setToolTipText("Salvar");
        buttonEditUser.setAutoscrolls(true);
        buttonEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditUserActionPerformed(evt);
            }
        });

        buttonDeleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/256-256-c020ce89b5c951e08148e0.png"))); // NOI18N
        buttonDeleteUser.setToolTipText("Salvar");
        buttonDeleteUser.setAutoscrolls(true);
        buttonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEditUsuLayout = new javax.swing.GroupLayout(PanelEditUsu);
        PanelEditUsu.setLayout(PanelEditUsuLayout);
        PanelEditUsuLayout.setHorizontalGroup(
            PanelEditUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditUsuLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(buttonEditUser)
                .addGap(55, 55, 55)
                .addComponent(buttonDeleteUser)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelEditUsuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(PanelEditUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEditUsuLayout.createSequentialGroup()
                        .addGroup(PanelEditUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9))
                        .addGap(53, 53, 53)
                        .addGroup(PanelEditUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEditCSenha)
                            .addGroup(PanelEditUsuLayout.createSequentialGroup()
                                .addGroup(PanelEditUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textEditNomeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelEditUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textEditEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                                        .addComponent(textEditSenha)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(38, 38, 38))
                    .addGroup(PanelEditUsuLayout.createSequentialGroup()
                        .addGroup(PanelEditUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(LabelEditUsu))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelEditUsuLayout.setVerticalGroup(
            PanelEditUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEditUsuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(LabelEditUsu)
                .addGap(46, 46, 46)
                .addGroup(PanelEditUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEditNomeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEditUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEditUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEditSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEditUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEditCSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161)
                .addGroup(PanelEditUsuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        PanelRoot.add(PanelEditUsu, "PanelEditUsu");

        PanelCadJogo.setBackground(new java.awt.Color(236, 239, 249));

        LabelCadUsu1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelCadUsu1.setText("CADASTRAR JOGO");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Nome:");

        textNomeJogo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Desenvolvedora:");

        textDesenvolvedora.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Gênero:");

        buttonCadastrarUsuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/b8013d3077f62d29bce2664db69424.png"))); // NOI18N
        buttonCadastrarUsuario2.setAutoscrolls(true);
        buttonCadastrarUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarUsuario2ActionPerformed(evt);
            }
        });

        comboGeneroJogo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ação/Aventura", "Beat Em up", "Cartas", "Construção/gerenciamento", "Corrida", "Educativo", "Esportes", "Estratégia", "FPS", "Hack'n Slash", "Infantil", "Luta", "MMO", "MOBA", "Música/ritmo", "Plataforma", "Puzzle", "RPG", "Simulador", "Stealth", "Survivor Horror", "Terror", "Turn Based" }));
        comboGeneroJogo.setPreferredSize(new java.awt.Dimension(98, 25));
        comboGeneroJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGeneroJogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCadJogoLayout = new javax.swing.GroupLayout(PanelCadJogo);
        PanelCadJogo.setLayout(PanelCadJogoLayout);
        PanelCadJogoLayout.setHorizontalGroup(
            PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadJogoLayout.createSequentialGroup()
                .addGroup(PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadJogoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCadJogoLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(117, 117, 117)
                                .addComponent(comboGeneroJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelCadUsu1)
                            .addGroup(PanelCadJogoLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(66, 66, 66)
                                .addComponent(textDesenvolvedora, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelCadJogoLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(126, 126, 126)
                                .addComponent(textNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelCadJogoLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(buttonCadastrarUsuario2)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        PanelCadJogoLayout.setVerticalGroup(
            PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadJogoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(LabelCadUsu1)
                .addGap(49, 49, 49)
                .addGroup(PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDesenvolvedora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCadJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboGeneroJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(buttonCadastrarUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        PanelRoot.add(PanelCadJogo, "cadastrarJogo");

        PanelCadJogo1.setBackground(new java.awt.Color(236, 239, 249));

        LabelEditJogo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelEditJogo.setText("EDITAR JOGO");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Nome:");

        editNomeJogo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        editNomeJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNomeJogoActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Desenvolvedora:");

        editDesenvolvedora.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Gênero:");

        buttonAvancarEditJogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/b8013d3077f62d29bce2664db69424.png"))); // NOI18N
        buttonAvancarEditJogo.setAutoscrolls(true);
        buttonAvancarEditJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAvancarEditJogoActionPerformed(evt);
            }
        });

        editGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FPS", "Terror", "Ação/Aventura", "RPG", "Plataforma", "Luta", "Corrida", "Esportes" }));
        editGenero.setSelectedIndex(-1);
        editGenero.setToolTipText("");
        editGenero.setPreferredSize(new java.awt.Dimension(98, 25));
        editGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editGeneroActionPerformed(evt);
            }
        });

        deleteJogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/256-256-c020ce89b5c951e08148e0.png"))); // NOI18N
        deleteJogo.setToolTipText("Salvar");
        deleteJogo.setAutoscrolls(true);
        deleteJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJogoActionPerformed(evt);
            }
        });

        avaliar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Honeyview_rating.png"))); // NOI18N
        avaliar.setText("Avaliar");
        avaliar.setAutoscrolls(true);
        avaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCadJogo1Layout = new javax.swing.GroupLayout(PanelCadJogo1);
        PanelCadJogo1.setLayout(PanelCadJogo1Layout);
        PanelCadJogo1Layout.setHorizontalGroup(
            PanelCadJogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadJogo1Layout.createSequentialGroup()
                .addGroup(PanelCadJogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCadJogo1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(PanelCadJogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelEditJogo)
                            .addGroup(PanelCadJogo1Layout.createSequentialGroup()
                                .addGroup(PanelCadJogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel31))
                                .addGap(117, 117, 117)
                                .addGroup(PanelCadJogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelCadJogo1Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(66, 66, 66)
                                .addComponent(editDesenvolvedora, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelCadJogo1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(avaliar)
                        .addGap(55, 55, 55)
                        .addComponent(buttonAvancarEditJogo)
                        .addGap(57, 57, 57)
                        .addComponent(deleteJogo)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        PanelCadJogo1Layout.setVerticalGroup(
            PanelCadJogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadJogo1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(LabelEditJogo)
                .addGap(49, 49, 49)
                .addGroup(PanelCadJogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCadJogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editDesenvolvedora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCadJogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addGroup(PanelCadJogo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAvancarEditJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avaliar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );

        PanelRoot.add(PanelCadJogo1, "editGame");

        PanelListGame.setBackground(new java.awt.Color(236, 239, 249));
        PanelListGame.setPreferredSize(new java.awt.Dimension(606, 560));

        LabelListGame.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelListGame.setText("BUSCAR JOGOS");

        jTextFieldSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldSearch.setToolTipText("Infome o nome do jogo");
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_33363 (1).png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(63, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tabela);

        jButton2.setText("Gerar relatório completo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Gerar relatório por gênero");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Gerar relatório desenvolvedora");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelListGameLayout = new javax.swing.GroupLayout(PanelListGame);
        PanelListGame.setLayout(PanelListGameLayout);
        PanelListGameLayout.setHorizontalGroup(
            PanelListGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListGameLayout.createSequentialGroup()
                .addGroup(PanelListGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelListGameLayout.createSequentialGroup()
                        .addGroup(PanelListGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelListGameLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelListGameLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(LabelListGame)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelListGameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelListGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, PanelListGameLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(44, 44, 44)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(jButton4)))))
                .addContainerGap())
        );
        PanelListGameLayout.setVerticalGroup(
            PanelListGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListGameLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(LabelListGame)
                .addGap(8, 8, 8)
                .addGroup(PanelListGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelListGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        PanelRoot.add(PanelListGame, "PanelListGame");

        PanelListAva.setBackground(new java.awt.Color(236, 239, 249));
        PanelListAva.setPreferredSize(new java.awt.Dimension(606, 560));

        LabelListGame1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelListGame1.setText("LISTAR AVALIAÇÕES");

        tabelaAval.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tabelaAval);

        editarAval.setText("Editar");
        editarAval.setAutoscrolls(true);
        editarAval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarAvalActionPerformed(evt);
            }
        });

        minhasAval1.setText("Minhas avaliações");
        minhasAval1.setAutoscrolls(true);
        minhasAval1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minhasAval1ActionPerformed(evt);
            }
        });

        excluirAval.setText("Excluir");
        excluirAval.setAutoscrolls(true);
        excluirAval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirAvalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelListAvaLayout = new javax.swing.GroupLayout(PanelListAva);
        PanelListAva.setLayout(PanelListAvaLayout);
        PanelListAvaLayout.setHorizontalGroup(
            PanelListAvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListAvaLayout.createSequentialGroup()
                .addGroup(PanelListAvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelListAvaLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(LabelListGame1)
                        .addGap(161, 161, 161)
                        .addComponent(minhasAval1))
                    .addGroup(PanelListAvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PanelListAvaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(excluirAval)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(editarAval)
                            .addGap(8, 8, 8))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelListAvaLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        PanelListAvaLayout.setVerticalGroup(
            PanelListAvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListAvaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PanelListAvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelListGame1)
                    .addComponent(minhasAval1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(PanelListAvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        PanelRoot.add(PanelListAva, "PanelListAva");

        LabelCadAval.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelCadAval.setText("CADASTRAR AVALIAÇÃO");

        labelNomeAval.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelNomeAval.setText("Nome:");
        labelNomeAval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                labelNomeAvalKeyTyped(evt);
            }
        });

        textNomeAval.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textNomeAval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeAvalActionPerformed(evt);
            }
        });

        labelDev.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelDev.setText("Desenvolvedora:");

        textDevAval.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        labelGen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelGen.setText("Gênero:");

        comboGenAval.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FPS", "Terror", "Ação/Aventura", "RPG", "Plataforma", "Luta", "Corrida", "Esportes" }));
        comboGenAval.setSelectedIndex(-1);
        comboGenAval.setToolTipText("");
        comboGenAval.setPreferredSize(new java.awt.Dimension(98, 25));
        comboGenAval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGenAvalActionPerformed(evt);
            }
        });

        labelNota.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelNota.setText("Nota:");

        textNota.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        textNota.setPreferredSize(new java.awt.Dimension(6, 25));
        textNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNotaActionPerformed(evt);
            }
        });

        labelAval.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelAval.setText("Avaliação:");

        textAval.setColumns(20);
        textAval.setRows(5);
        jScrollPane7.setViewportView(textAval);

        salvarAval.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/b8013d3077f62d29bce2664db69424.png"))); // NOI18N
        salvarAval.setAutoscrolls(true);
        salvarAval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarAvalActionPerformed(evt);
            }
        });

        editarAvaliacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/b8013d3077f62d29bce2664db69424.png"))); // NOI18N
        editarAvaliacao.setAutoscrolls(true);
        editarAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarAvaliacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCadAvalLayout = new javax.swing.GroupLayout(PanelCadAval);
        PanelCadAval.setLayout(PanelCadAvalLayout);
        PanelCadAvalLayout.setHorizontalGroup(
            PanelCadAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadAvalLayout.createSequentialGroup()
                .addContainerGap(309, Short.MAX_VALUE)
                .addComponent(editarAvaliacao)
                .addGap(244, 244, 244))
            .addGroup(PanelCadAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelCadAvalLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(PanelCadAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelCadAval)
                        .addGroup(PanelCadAvalLayout.createSequentialGroup()
                            .addGroup(PanelCadAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelNomeAval)
                                .addComponent(labelGen))
                            .addGap(117, 117, 117)
                            .addGroup(PanelCadAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textNomeAval, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboGenAval, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelCadAvalLayout.createSequentialGroup()
                            .addComponent(labelDev)
                            .addGap(66, 66, 66)
                            .addComponent(textDevAval, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelCadAvalLayout.createSequentialGroup()
                            .addGroup(PanelCadAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelNota)
                                .addComponent(labelAval))
                            .addGap(103, 103, 103)
                            .addGroup(PanelCadAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textNota, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelCadAvalLayout.createSequentialGroup()
                            .addGap(220, 220, 220)
                            .addComponent(salvarAval)))
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
        PanelCadAvalLayout.setVerticalGroup(
            PanelCadAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadAvalLayout.createSequentialGroup()
                .addContainerGap(471, Short.MAX_VALUE)
                .addComponent(editarAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(PanelCadAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelCadAvalLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(LabelCadAval)
                    .addGap(49, 49, 49)
                    .addGroup(PanelCadAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNomeAval, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNomeAval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(PanelCadAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDev, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textDevAval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(PanelCadAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelGen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboGenAval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(PanelCadAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNota, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(PanelCadAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelAval, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                    .addComponent(salvarAval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(70, 70, 70)))
        );

        PanelRoot.add(PanelCadAval, "avaliacaoJogo");

        PanelLateral.setBackground(new java.awt.Color(43, 64, 136));
        PanelLateral.setPreferredSize(new java.awt.Dimension(200, 579));
        PanelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEditUsu.setBackground(new java.awt.Color(236, 239, 249));
        jButtonEditUsu.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonEditUsu.setText("Editar Usuário");
        jButtonEditUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditUsuActionPerformed(evt);
            }
        });
        PanelLateral.add(jButtonEditUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 50));

        jButtonLogoff.setBackground(new java.awt.Color(236, 239, 249));
        jButtonLogoff.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonLogoff.setText("Sair");
        jButtonLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoffActionPerformed(evt);
            }
        });
        PanelLateral.add(jButtonLogoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 200, 50));

        jButtonCadJogo.setBackground(new java.awt.Color(236, 239, 249));
        jButtonCadJogo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonCadJogo.setText("Cadastrar Jogo");
        jButtonCadJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadJogoActionPerformed(evt);
            }
        });
        PanelLateral.add(jButtonCadJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 50));

        jButtonListGames.setBackground(new java.awt.Color(236, 239, 249));
        jButtonListGames.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonListGames.setText("Buscar Jogos");
        jButtonListGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListGamesActionPerformed(evt);
            }
        });
        PanelLateral.add(jButtonListGames, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 50));

        jButtonListAva.setBackground(new java.awt.Color(236, 239, 249));
        jButtonListAva.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonListAva.setText("Listar Avaliações");
        jButtonListAva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListAvaActionPerformed(evt);
            }
        });
        PanelLateral.add(jButtonListAva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, 50));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/video-game-emoji-png-7-2.png"))); // NOI18N
        PanelLateral.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(PanelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastrarUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarUsuario2ActionPerformed

        ArrayList novaLista = new ArrayList();

        try {
            //Capturando informações e adicionando a uma lista
            novaLista.add(textNomeJogo.getText());
            novaLista.add(textDesenvolvedora.getText());
            novaLista.add(comboGeneroJogo.getSelectedItem());
            
            
            //Mandando para o Contoller
            if (controlJogo.criarJogo(novaLista)) {
                JOptionPane.showMessageDialog(this, "O jogo foi salvo com sucesso!");
                textNomeJogo.setText("");
                textDesenvolvedora.setText("");
                comboGeneroJogo.setSelectedIndex(0);
                CardLayout card = (CardLayout) PanelRoot.getLayout();
                card.show(PanelRoot, "PanelInicial");
            }
        } catch (HeadlessException error) {
            String msgErro = "Erro: " + error;
            JOptionPane.showMessageDialog(this, msgErro);
        }
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "PanelInicial");
    
    }//GEN-LAST:event_buttonCadastrarUsuario2ActionPerformed

    private void jButtonCadJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadJogoActionPerformed
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "cadastrarJogo");
    }//GEN-LAST:event_jButtonCadJogoActionPerformed

    private void jButtonLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoffActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLogoffActionPerformed

    private void jButtonEditUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditUsuActionPerformed
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "PanelEditUsu");
        u.setEmail(Login.TextFieldLogin.getText());
        Usuario us = ud.select(u);
        textEditNomeUsu.setText(us.getNome());
        textEditEmail.setText(us.getEmail());
        textEditSenha.setText(us.getSenha());
        textEditCSenha.setText(us.getcSenha());
        textEditEmail.setEditable(false);
        
    }//GEN-LAST:event_jButtonEditUsuActionPerformed

    private void buttonEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditUserActionPerformed
        if(vc.camposVazios(textEditNomeUsu.getText(),textEditEmail.getText(),textEditSenha.getText(),textEditCSenha.getText())){
            if(textEditSenha.getText().equals(textEditCSenha.getText())){            
                u.setNome(textEditNomeUsu.getText());
                u.setEmail(textEditEmail.getText());
                u.setSenha(textEditSenha.getText());
                u.setcSenha(textEditCSenha.getText());
                ud.update(u);            
                JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "As senhas não conferem");
            }
        }   
    }//GEN-LAST:event_buttonEditUserActionPerformed

    private void textEditSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEditSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEditSenhaActionPerformed

    private void textEditCSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEditCSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEditCSenhaActionPerformed

    private void textEditNomeUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEditNomeUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEditNomeUsuActionPerformed

    private void buttonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteUserActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "Deseja excluir usuario?\n(Você será levado a tela de login)");
        
        if(op == JOptionPane.YES_OPTION){
            ud.delete(textEditEmail.getText());
            new Login().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_buttonDeleteUserActionPerformed

    private void buttonAvancarEditJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAvancarEditJogoActionPerformed
        try {
            String editNome = editNomeJogo.getText();
            String editDev = editDesenvolvedora.getText();
            String editGeneroJogo = editGenero.getModel().getSelectedItem().toString();
            
            //System.out.println("ESSE " + editDev);
            
            ArrayList novaLista = new ArrayList();
            novaLista.add(editNome);
            novaLista.add(editDev);
            novaLista.add(editGeneroJogo);

            if (controlJogo.editarJogo(novaLista)) {
                JOptionPane.showMessageDialog(this, "As alterações foram salvas com sucesso!");
                CardLayout card = (CardLayout) PanelRoot.getLayout();
                card.show(PanelRoot, "PanelInicial");
            } 
        } catch (HeadlessException error) {
            System.err.println("Erro: " + error);
        }
        //jTabbedEditJogo.setSelectedIndex(1);
    }//GEN-LAST:event_buttonAvancarEditJogoActionPerformed

    private void jButtonListGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListGamesActionPerformed
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "PanelListGame");
        Connection connection = null;
        StringBuilder campos = new StringBuilder();
        campos.append("*");
        controlBD.ExecutaQuery(connection, "jogo", campos);
        ResultSet rs = controlBD.retornaConsulta();
        
        String[] colunasNomes = {"Nome", "Desenvolvedor", "Genero"};
        DefaultTableModel model = (DefaultTableModel)tabela.getModel();
        model.getDataVector().removeAllElements();
        model.setColumnIdentifiers(colunasNomes);
        ResultSetMetaData rsmd;
        try {
            rsmd = rs.getMetaData();
            int colNum = rsmd.getColumnCount();
        while(rs.next()){
            Object[] objects = new Object[colNum];
            for(int i = 0; i < colNum; i++){
                objects[i] = rs.getObject(i+1);
            }
            model.addRow(objects);
        }
        
        tabela.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //controlBD.Sair();
        

    }//GEN-LAST:event_jButtonListGamesActionPerformed

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Connection connection = null;
        String campos;
        campos = jTextFieldSearch.getText();
        controlBD.ExecutaQuery(connection, "jogo", "jogo_nome",campos);
        ResultSet rs = controlBD.retornaConsulta();
        
        try {
            rs.next();
            //faz a leitura do registro corrento do ResutSet e atribui os valores lidos aos objetos visuais (Textfields)
            editNomeJogo.setText(rs.getString("jogo_nome"));
            editDesenvolvedora.setText(rs.getString("jogo_dev"));
            editGenero.setSelectedItem(rs.getString("jogo_gen"));
            textNomeAval.setText(editNomeJogo.getText());
            textDevAval.setText(editDesenvolvedora.getText());
            comboGenAval.setSelectedItem(editGenero.getSelectedItem());
        } catch (Exception erro) {
            System.out.println(erro);
        }
        editNomeJogo.setEditable(false);
        
        jTextFieldSearch.setText("");
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "editGame");
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editNomeJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNomeJogoActionPerformed
        
    }//GEN-LAST:event_editNomeJogoActionPerformed

    private void textEditEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEditEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEditEmailActionPerformed

    private void jButtonListAvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListAvaActionPerformed
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "PanelListAva");
        excluirAval.setVisible(false);
        editarAval.setVisible(false);
        Connection connection = null;
        StringBuilder campos = new StringBuilder();
        campos.append("*");
        controlBD.ExecutaQuery(connection, "avaliacao", campos);
        ResultSet rs = controlBD.retornaConsulta();
        
        String[] colunasNomes = {"Nota", "Comentario", "Email", "Jogo"};
        DefaultTableModel modelAval = (DefaultTableModel)tabelaAval.getModel();
        modelAval.getDataVector().removeAllElements();
        modelAval.setColumnIdentifiers(colunasNomes);
        ResultSetMetaData rsmd;
        try {
            rsmd = rs.getMetaData();
            int colNum = rsmd.getColumnCount();
        while(rs.next()){
            Object[] objects = new Object[colNum];
            for(int i = 0; i < colNum; i++){
                objects[i] = rs.getObject(i+1);
            }
            modelAval.addRow(objects);
        }
        
        tabelaAval.setModel(modelAval);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        //TODO LISTAR AVALIAÇAO
    }//GEN-LAST:event_jButtonListAvaActionPerformed

    private void deleteJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJogoActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseja excluir o jogo?") == 0){
            AvaliacaoDAO.delete(editNomeJogo.getText());
            controlJogo.excluirJogo(editNomeJogo.getText());
            JOptionPane.showMessageDialog(null, "Deletado com sucesso");
        }
        
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "PanelInicial");
        
    }//GEN-LAST:event_deleteJogoActionPerformed

    private void editGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editGeneroActionPerformed

    private void textNomeAvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeAvalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeAvalActionPerformed

    private void comboGenAvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGenAvalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboGenAvalActionPerformed

    private void textNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNotaActionPerformed

    private void salvarAvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarAvalActionPerformed
        try {
            u.setEmail(Login.TextFieldLogin.getText());
            String editNota = textNota.getText();
            String editAval = textAval.getText();
            String editJogoAval = textNomeAval.getText();
            String editNotaC = editNota.replace(',','.');
            
            j.setNome(editJogoAval);
            //System.out.println("JOGO : "+j.getNome());
            //System.out.println("USU : "+u.getEmail());
            ArrayList novaLista = new ArrayList();
            novaLista.add(parseDouble(editNotaC));
            novaLista.add(editAval);
            novaLista.add(u);
            novaLista.add(j);

            if (controlAval.criarAval(novaLista)) {
                JOptionPane.showMessageDialog(this, "Avaliação salva com sucesso!");
                textNota.setText("");
                textAval.setText("");
                CardLayout card = (CardLayout) PanelRoot.getLayout();
                card.show(PanelRoot, "editarJogo");
            } 
        } catch (HeadlessException error) {
            System.err.println("Erro: " + error);
        }
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "PanelListGame");
    }//GEN-LAST:event_salvarAvalActionPerformed

    private void labelNomeAvalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labelNomeAvalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_labelNomeAvalKeyTyped

    private void avaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliarActionPerformed
        CardLayout card = (CardLayout) PanelRoot.getLayout();
        card.show(PanelRoot, "avaliacaoJogo");
        labelGen.setVisible(true);
        labelDev.setVisible(true);
        labelNomeAval.setVisible(true);
        textNomeAval.setVisible(true);
        textDevAval.setVisible(true);
        comboGenAval.setVisible(true);
        textNomeAval.setEditable(false);
        textDevAval.setEditable(false);
        comboGenAval.setEditable(false);
        comboGenAval.setEnabled(false);
        editarAvaliacao.setVisible(false);
        salvarAval.setVisible(true);
    }//GEN-LAST:event_avaliarActionPerformed

    private void editarAvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarAvalActionPerformed
        try {
            int selectedRowIndex = tabelaAval.getSelectedRow();
            if (selectedRowIndex >= 0) {
                String nome = tabelaAval.getModel().
                        getValueAt(selectedRowIndex, 2).toString();
                String jogo = tabelaAval.getModel().
                        getValueAt(selectedRowIndex, 3).toString();
                u.setEmail(nome);
                j.setNome(jogo);
                int confirm = JOptionPane.showConfirmDialog(this,
                        "Deseja editar a avaliacao do jogo " + jogo + "?");
                if (confirm == 0) {
                    DefaultTableModel modelAval = (DefaultTableModel) tabelaAval.getModel();
                    CardLayout card = (CardLayout) PanelRoot.getLayout();
                    card.show(PanelRoot, "avaliacaoJogo");
                    labelGen.setVisible(false);
                    labelDev.setVisible(false);
                    labelNomeAval.setVisible(false);
                    textNomeAval.setVisible(false);
                    textDevAval.setVisible(false);
                    comboGenAval.setVisible(false);
                    comboGenAval.setEnabled(false);
                    editarAvaliacao.setVisible(true);
                    salvarAval.setVisible(false);
                    Connection connection = null;
                    controlBD.ExecutaQuery("SELECT * FROM avaliacao WHERE usu_email_fk = '"+nome+"' AND jogo_nome_fk = '"+jogo+"' ;");
                    ResultSet rs = controlBD.retornaConsulta();
                    rs.next();
                    textNota.setText(rs.getString("nota"));
                    textAval.setText(rs.getString("comentario"));
                    
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nenhuma avaliacao selecionada");
            }
        } catch (HeadlessException error) {
            String msgError = "Erro: " + error;
            JOptionPane.showMessageDialog(this, error);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarAvalActionPerformed

    private void minhasAval1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minhasAval1ActionPerformed
        excluirAval.setVisible(true);
        editarAval.setVisible(true);
        Connection connection = null;
        StringBuilder campos = new StringBuilder();
        u.setEmail(Login.TextFieldLogin.getText());
        campos.append("*");
        controlBD.ExecutaQuery(connection, "avaliacao", campos, u.getEmail());
        ResultSet rs = controlBD.retornaConsulta();
        
        String[] colunasNomes = {"Nota", "Comentario", "Email", "Jogo"};
        DefaultTableModel modelAval = (DefaultTableModel)tabelaAval.getModel();
        modelAval.getDataVector().removeAllElements();
        modelAval.setColumnIdentifiers(colunasNomes);
        ResultSetMetaData rsmd;
        try {
            rsmd = rs.getMetaData();
            int colNum = rsmd.getColumnCount();
        while(rs.next()){
            Object[] objects = new Object[colNum];
            for(int i = 0; i < colNum; i++){
                objects[i] = rs.getObject(i+1);
            }
            modelAval.addRow(objects);
        }
        
        tabelaAval.setModel(modelAval);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_minhasAval1ActionPerformed

    private void excluirAvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirAvalActionPerformed
        try {
            int selectedRowIndex = tabelaAval.getSelectedRow();
            if (selectedRowIndex >= 0) {
                String nome = tabelaAval.getModel().
                        getValueAt(selectedRowIndex, 2).toString();
                String jogo = tabelaAval.getModel().
                        getValueAt(selectedRowIndex, 3).toString();
                u.setEmail(nome);
                j.setNome(jogo);
                int confirm = JOptionPane.showConfirmDialog(this,
                        "Deseja realmente excluir a avaliacao do jogo " + jogo + "?");
                if (confirm == 0) {
                    DefaultTableModel modelAval = (DefaultTableModel) tabelaAval.getModel();
                    controlAval.excluirAval(u,j);
                    modelAval.removeRow(selectedRowIndex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nenhuma avaliacao selecionada");
            }
        } catch (HeadlessException error) {
            String msgError = "Erro: " + error;
            JOptionPane.showMessageDialog(this, error);
        }
    }//GEN-LAST:event_excluirAvalActionPerformed

    private void editarAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarAvaliacaoActionPerformed
        
        try{
         String editNota = textNota.getText();
         String editAval = textAval.getText();
         String editNotaCert = editNota.replace(',','.');
         
         ArrayList novaLista = new ArrayList();
            novaLista.add(parseDouble(editNotaCert));
            novaLista.add(editAval);
            novaLista.add(u);
            novaLista.add(j);

            if (controlAval.editarAval(novaLista)) {
                JOptionPane.showMessageDialog(this, "As alterações foram salvas com sucesso!");
                CardLayout card = (CardLayout) PanelRoot.getLayout();
                card.show(PanelRoot, "PanelInicial");
            } 
        } catch (HeadlessException error) {
            System.err.println("Erro: " + error);
        }
         
    }//GEN-LAST:event_editarAvaliacaoActionPerformed
      
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        rep.Relatorio(pdf, relatorio, null);        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        rep.Relatorio(pdf1, relatorio1, null);        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        rep.Relatorio(pdf2, relatorio2, JOptionPane.showInputDialog(null, "Digite a desenvolvedora desejada : "));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void comboGeneroJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGeneroJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboGeneroJogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FontFormatException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCadAval;
    private javax.swing.JLabel LabelCadUsu1;
    private javax.swing.JLabel LabelEditJogo;
    private javax.swing.JLabel LabelEditUsu;
    private javax.swing.JLabel LabelListGame;
    private javax.swing.JLabel LabelListGame1;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelCadAval;
    private javax.swing.JPanel PanelCadJogo;
    private javax.swing.JPanel PanelCadJogo1;
    private javax.swing.JPanel PanelEditUsu;
    private javax.swing.JPanel PanelInicial;
    private javax.swing.JPanel PanelLateral;
    private javax.swing.JPanel PanelListAva;
    private javax.swing.JPanel PanelListGame;
    private javax.swing.JPanel PanelRoot;
    private javax.swing.JButton avaliar;
    private javax.swing.JButton buttonAvancarEditJogo;
    private javax.swing.JButton buttonCadastrarUsuario2;
    private javax.swing.JButton buttonDeleteUser;
    private javax.swing.JButton buttonEditUser;
    private javax.swing.JComboBox<String> comboGenAval;
    private javax.swing.JComboBox<String> comboGeneroJogo;
    private javax.swing.JButton deleteJogo;
    private javax.swing.JTextField editDesenvolvedora;
    private javax.swing.JComboBox<String> editGenero;
    private javax.swing.JTextField editNomeJogo;
    private javax.swing.JButton editarAval;
    private javax.swing.JButton editarAvaliacao;
    private javax.swing.JButton excluirAval;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonCadJogo;
    private javax.swing.JButton jButtonEditUsu;
    private javax.swing.JButton jButtonListAva;
    private javax.swing.JButton jButtonListGames;
    private javax.swing.JButton jButtonLogoff;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JLabel labelAval;
    private javax.swing.JLabel labelDev;
    private javax.swing.JLabel labelGen;
    private javax.swing.JLabel labelNomeAval;
    private javax.swing.JLabel labelNota;
    private javax.swing.JButton minhasAval1;
    private javax.swing.JButton salvarAval;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabelaAval;
    private javax.swing.JTextArea textAval;
    private javax.swing.JTextField textDesenvolvedora;
    private javax.swing.JTextField textDevAval;
    private javax.swing.JPasswordField textEditCSenha;
    private javax.swing.JTextField textEditEmail;
    private javax.swing.JTextField textEditNomeUsu;
    private javax.swing.JPasswordField textEditSenha;
    private javax.swing.JTextField textNomeAval;
    private javax.swing.JTextField textNomeJogo;
    private javax.swing.JFormattedTextField textNota;
    // End of variables declaration//GEN-END:variables
}
